services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: uv run python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    command: npm run build && npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_DJANGO_API_URL=https://django-backend-50284710838.europe-west1.run.app
    depends_on:
      - backend
